
import { jsPDF } from 'jspdf';
import * as XLSX from 'xlsx';
import pptxgen from 'pptxgenjs';
import html2canvas from 'html2canvas';
import { SurveyResponse, Bank } from '../types';
import { DashboardMetrics, TrendData, CompetitorData } from './api';

export interface ExportSettings {
  includeExecutiveSummary: boolean;
  includeDetailedMetrics: boolean;
  includeCompetitiveAnalysis: boolean;
  includeRawData: boolean;
  bankName: string;
}

export const generateAdvancedExcel = (
  responses: SurveyResponse[],
  metrics: DashboardMetrics | null,
  trends: TrendData[],
  competitors: CompetitorData[]
) => {
  const wb = XLSX.utils.book_new();

  // Sheet 1: Dashboard Overview
  if (metrics) {
    const dashboardData = [
      ['METRIC', 'VALUE', 'MARKET RANK', 'CHANGE %'],
      ['Top-of-Mind Awareness', `${metrics.metrics.topOfMind.value}%`, metrics.metrics.topOfMind.rank, `+${metrics.metrics.topOfMind.change}%`],
      ['Net Promoter Score', metrics.metrics.nps.value, metrics.metrics.nps.rank, `${metrics.metrics.nps.change}%`],
      ['Brand Momentum', `${metrics.metrics.momentum.value}%`, metrics.metrics.momentum.rank, `+${metrics.metrics.momentum.change}%`],
      ['Future Consideration', `${metrics.metrics.consideration.value}%`, metrics.metrics.consideration.rank, `+${metrics.metrics.consideration.change}%`],
      [],
      ['NPS SEGMENTS', 'PERCENTAGE'],
      ['Promoters', `${metrics.metrics.nps.p}%`],
      ['Passives', `${metrics.metrics.nps.pass}%`],
      ['Detractors', `${metrics.metrics.nps.d}%`],
    ];
    const wsDashboard = XLSX.utils.aoa_to_sheet(dashboardData);
    XLSX.utils.book_append_sheet(wb, wsDashboard, 'Dashboard');
  }

  // Sheet 2: Raw Data
  const wsRaw = XLSX.utils.json_to_sheet(responses);
  XLSX.utils.book_append_sheet(wb, wsRaw, 'Raw Data');

  // Sheet 3: Trends
  const wsTrends = XLSX.utils.json_to_sheet(trends);
  XLSX.utils.book_append_sheet(wb, wsTrends, 'Trends');

  // Sheet 4: Competitors
  const wsCompetitors = XLSX.utils.json_to_sheet(competitors);
  XLSX.utils.book_append_sheet(wb, wsCompetitors, 'Competitive Benchmarking');

  XLSX.writeFile(wb, `Rwanda_Banking_Report_${new Date().toISOString().split('T')[0]}.xlsx`);
};

export const generateAdvancedPPT = async (
  metrics: DashboardMetrics | null,
  bankName: string
) => {
  const pres = new pptxgen();
  
  // Slide 1: Title Slide
  let slide1 = pres.addSlide();
  slide1.background = { fill: '0F172A' };
  slide1.addText('Market Intelligence Report 2026', { x: 1, y: 1.5, w: 8, fontSize: 44, bold: true, color: 'FFFFFF', fontFace: 'Arial' });
  slide1.addText(`Strategic Analysis for ${bankName}`, { x: 1, y: 2.5, w: 8, fontSize: 24, color: '3B82F6' });
  slide1.addText(`Generated: ${new Date().toLocaleDateString()}`, { x: 1, y: 5, w: 8, fontSize: 12, color: '94A3B8' });

  // Slide 2: Key Metrics
  if (metrics) {
    let slide2 = pres.addSlide();
    slide2.addText('Executive KPI Summary', { x: 0.5, y: 0.5, fontSize: 28, bold: true, color: '0F172A' });
    
    const rows = [
        ['Metric', 'Score', 'Rank'],
        ['Top-of-Mind Awareness', `${metrics.metrics.topOfMind.value}%`, `#${metrics.metrics.topOfMind.rank}`],
        ['Net Promoter Score', `${metrics.metrics.nps.value}`, `#${metrics.metrics.nps.rank}`],
        ['Brand Momentum', `${metrics.metrics.momentum.value}%`, `#${metrics.metrics.momentum.rank}`],
        ['Future Consideration', `${metrics.metrics.consideration.value}%`, `#${metrics.metrics.consideration.rank}`],
    ];
    slide2.addTable(rows, { x: 0.5, y: 1.5, w: 9, h: 4, border: { pt: 1, color: 'E2E8F0' }, fill: { color: 'F8FAFC' } });
  }

  pres.writeFile({ fileName: `Banking_Presentation_${bankName.replace(/\s+/g, '_')}.pptx` });
};

export const generateAdvancedPDF = async (
  containerId: string,
  settings: ExportSettings,
  metrics: DashboardMetrics | null
) => {
  const pdf = new jsPDF('p', 'mm', 'a4');
  const element = document.getElementById(containerId);
  
  if (!element) return;

  // Cover Page
  pdf.setFillColor(15, 23, 42); // Navy background
  pdf.rect(0, 0, 210, 297, 'F');
  
  pdf.setTextColor(255, 255, 255);
  pdf.setFontSize(32);
  pdf.text('BRAND HEALTH REPORT', 105, 100, { align: 'center' });
  pdf.setFontSize(18);
  pdf.setTextColor(59, 130, 246); // Blue
  pdf.text(settings.bankName.toUpperCase(), 105, 115, { align: 'center' });
  
  pdf.setFontSize(10);
  pdf.setTextColor(148, 163, 184); // Slate
  pdf.text(`REPORTING PERIOD: JAN 2026`, 105, 260, { align: 'center' });
  pdf.text(`GENERATED BY MARKETPULSE ANALYTICS v4.2`, 105, 267, { align: 'center' });

  // Page 2: Dashboard Capture
  if (settings.includeExecutiveSummary || settings.includeDetailedMetrics) {
    pdf.addPage();
    const canvas = await html2canvas(element, {
        scale: 2,
        useCORS: true,
        backgroundColor: '#0f172a'
    });
    
    const imgData = canvas.toDataURL('image/png');
    const imgProps = pdf.getImageProperties(imgData);
    const pdfWidth = pdf.internal.pageSize.getWidth();
    const pdfHeight = (imgProps.height * pdfWidth) / imgProps.width;
    
    // If the dashboard is very tall, we might need multiple pages or scaling
    pdf.addImage(imgData, 'PNG', 0, 0, pdfWidth, pdfHeight);
  }

  pdf.save(`Executive_Report_${settings.bankName.replace(/\s+/g, '_')}.pdf`);
};
